### ISSUE TITLE
3D function can not be displayed from the visualizer

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#406]
THREE.WebGLRenderer 68
348three.min.js:572 Uncaught SecurityError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at http://www.lactame.com/visualizer/v2.13.0/modules/types/chart/advanced/plot_function/square.png may not be loaded.three.min.js:572 setTexturethree.min.js:509 zthree.min.js:544 renderBufferthree.min.js:483 vthree.min.js:556 renderview.js:1 $.extend.animate

Testcase: http://visualizer.epfl.ch/tiny/nI7QVDz1XFLi6R1uLwQ9 ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F65f84b002399eb79ec0f8bf145483610%2Fview.json&v=v2.13.0))

**Comment by lpatiny** [comment]
https://github.com/mrdoob/three.js/issues/687

**Comment by lpatiny** [comment]
Fixed

**Comment by stropitek** [comment]
I had already done ```this.THREE.ImageUtils.crossOrigin = '';``` in the init script of THREEJS so that it is global.

It fixes it on lactame.com but I still have a cross origin error on visualizer.epfl.ch
[http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F65f84b002399eb79ec0f8bf1454c5445%2Fview.json](here)

**Comment by stropitek** [comment]
My bad... It work on the head
